package com.fluxtion.example.jmh.pricer.builder;

import com.fluxtion.compiler.EventProcessorConfig;
import com.fluxtion.compiler.FluxtionCompilerConfig;
import com.fluxtion.compiler.FluxtionGraphBuilder;
import com.fluxtion.example.jmh.pricer.node.PriceLadderPublisher;

/**
 * Build the PriceLadderProcessorNoBranching AOT with the maven plugin
 * <p>
 * The dirty filtering support is disabled in buildGraph, results in no branches in the dispatch code generated by the
 * Fluxtion compiler.
 */
public class PriceCalculatorNoBranchingAotBuilder implements FluxtionGraphBuilder {
    @Override
    public void buildGraph(EventProcessorConfig eventProcessorConfig) {
        eventProcessorConfig.addNode(new PriceLadderPublisher());
        //this line disables the dirty flag checking in the dispatch code
        eventProcessorConfig.setSupportDirtyFiltering(false);
    }

    @Override
    public void configureGeneration(FluxtionCompilerConfig fluxtionCompilerConfig) {
        fluxtionCompilerConfig.setClassName("PriceLadderProcessorNoBranching");
        fluxtionCompilerConfig.setPackageName("com.fluxtion.example.jmh.pricer.generated");
    }
}
